name: build test
kind: pipeline
type: docker
steps:
  - name: build
    image: golang:1.13
    commands:
      - go get github.com/fogleman/gg
      - go get github.com/bwmarrin/discordgo
      - go get github.com/BurntSushi/toml
      - go get github.com/FlameInTheDark/gopus
      - go get github.com/globalsign/mgo
      - go get gopkg.in/robfig/cron.v2
      - go build

  - name: discrod notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_wh_id
      webhook_token:
        from_secret: discord_wh_token

trigger:
  branch:
    - master
  event:
    - push