name: build test
kind: pipeline
type: docker

workspace:
  base: /go
  path: src/github.com/FlameInTheDark/dtbot

steps:
  - name: build
    image: golang:1.13
    commands:
      - go get ./...
      - go build

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_wh_id
      webhook_token:
        from_secret: discord_wh_token

trigger:
  branch:
    - master
  event:
    - push